<svelte:head>
  <title>Terms of Service - MyCamFinder</title>
  <meta name="description" content="Learn more about Dimecams and our mission to bring you the best live cam experience." />
</svelte:head>

<section class="max-w-4xl mx-auto py-20 px-6 text-gray-100">
  <h1 class="text-3xl font-bold mb-4">Terms Of Service</h1>

  <p>MYCAMFINDER.COM and its affiliates or assigns operates and manages the Website platform accessible at www.MYCAMFINDER.com including all its subdomains, where users can view a conglomeration of webcam models from a various third party websites the platform provides explicit adult entertainment and is only open to consenting adults</p>
<p>These Terms of Service (&ldquo;TOS&rdquo;) constitute a binding agreement between you (the viewer) and MYCAMFINDER.com &ldquo;MYCAMFINDER&rdquo; &ldquo;CF&rdquo; regarding your use of the MYCAMFINDER website (the &ldquo;Site&rdquo;). Please read this Agreement carefully. By using the Site you agree to be bound by these TOS. If you do not agree to any provision of this Agreement, you should not use the Site.</p>
<p>By using the Site you agree that YOU HAVE READ AND UNDERSTAND THESE TERMS OF SERVICE AND AGREE TO BE BOUND BY THEM. If any provision of these TOS is found invalid or unenforceable, that provision will be enforced to the maximum extent permissible and all other provisions of the TOS will remain in force.</p>
<p>By accessing the Site you represent and warrant that you are at least 18 years old, that you have reached the legal age determined by the governing law of your country to view sexually explicit material, that you are accessing the Site from a location where the content of the Site is legal and permitted, and that you will not permit any other person to access the Site who is not allowed to do so. Access to materials appearing on this Site from jurisdictions where its contents are illegal is prohibited.</p>
<p>You may not otherwise copy, redistribute, or steal the content of the Site, or create derivative works using that content. You understand and agree that the Site is provided to you on an AS IS and AS AVAILABLE basis. CF disclaims all responsibility and liability for the availability, timeliness, security or reliability of the Site, or any feature or software included in the Site. CF disclaims all responsibility or liability for the acts or omissions of third parties whose services, software, content, or advertising may be utilized in connection or appear on the Site, and you agree that CF will not be liable for any such services, software, content, or advertising. CF may be subject to occasional interruptions. You agree that CF will not be liable for any modification, suspension, interruption or discontinuance of the Site.</p>
<p>You will access and use the Site solely for your own personal use; You will comply with all applicable laws and regulations in using the Site and any content that appears on the Site; You will not use the Site in any illegal manner or for any illegal purpose, in any other manner that could damage, disable, overburden or impair the Site, or in any manner inconsistent with these TOS; You will not employ any automated system or tool to use the Site or obtain content or information from the Site; You will not defeat or interfere with any security feature of the Site, or attempt to do so; You will not alter or modify any content or component of the Site; and You will not reproduce, duplicate, copy, sell, trade, resell or exploit, for any commercial or personal purpose, any content or component of the Site or the cam shows provided by the models, or any use of or any access to the Site.</p>
<p>The Site may contain links to sponsor, advertiser, or other third party websites that are not owned or controlled by CF. Inclusion of, linking to, or permitting the use or installation of any third party site, applications, software, content or advertising does not imply approval or endorsement thereof by CF. CF has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third parties. By access or using the Site, you agree to release CF from any and all liability arising from your use of any third-party website, content, service, or software accessed on or through the Site.</p>
<p>CF reserves the right to access, read, preserve, and disclose any information as it reasonably believes is necessary to satisfy any applicable law, government request, enforce our TOS, prevent fraud, and theft. You agree to hold harmless and indemnify CF, and its subsidiaries, affiliates, officers, agents, and employees from and against any third-party claim arising from or in any way related to your use of the Site, including any liability or expense arising from all claims, losses, damages (actual and consequential), suits, judgments, litigation costs and attorneys&rsquo; fees, of every kind and nature. CF will make reasonable efforts to provide you with written notice of any such claim, suit or action, but the failure of CF to provide such notice will not relieve you of these obligations.</p>
<p>The failure of CF to exercise or enforce any right or provision of the TOS shall not constitute a waiver of such right or provision. If any provision of the TOS is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties&rsquo; intentions as reflected in the provision, and the other provisions of the TOS remain in full force and effect. These TOS may be revised from time to time. Notice will provided by updating the publish date on the TOS of CF. CF may restrict access to the site at any time if we believe a user is in violation of these TOS.</p>
<p>For models and material used with permission from third parties and its models, consider visiting the appropriate 2257 section found below:</p>

<h1 class="text-3xl font-bold mb-4">2257</h1>
<p>All of the models, actors, actresses and other persons that appear in any visual depiction of actual sexually explicit conduct appearing or otherwise contained in the following Website were over the age of eighteen years at the time of the creation of such depictions.</p>
<p>Moreover, as Mycamfinder.com is setup as an interactive computer service as defined under 47 U.S.C. &sect; 230(f), as well as an Internet access service as defined under 47 U.S.C. &sect; 231(e), that is statutorily exempt from being considered a producer under 18 U.S.C. &sect; 2257(h)(2)(B). This way, the owner of this Web site is not the primary producer (as that term is defined in 18 U.S.C. Section 2257) of some of the visual content contained in the Web site. However, Mycamfinder.com do strive to ensure that people on all media that appear on the site are over the age of 18.</p>
<p>In compliance with the Federal labeling and record keeping law United States Code, Title 18, Section 2257, all models who accept compensation for the content they upload and other persons who appear in any visual depiction of sexually explicit conduct appearing or otherwise contained in or at any Mycamfinder.com owned website were over the age of eighteen years at the time of the creation of such depictions. All content and images are in full compliance with the requirements of United States Code, Title 18, Section 2257 and associated regulations.</p>
<p>All other visual depictions displayed on this website are exempt from the provision of 18 U.S.C. section 2257 and 28 C.F.R. 75 because they do not portray conduct as specifically listed in 18 U.S.C section 2256 (2) (A) through (D), but are merely depictions of non-sexually explicit nudity, or are depictions of simulated sexual conduct, or are otherwise exempt because the visual depictions were created prior to July 3, 1995.</p>
</section>



<style>
  @reference "tailwindcss";

  :global(p) {
    @apply text-gray-200 mb-4 leading-relaxed;
  }
</style>

